### ISSUE TITLE
admin backend

### ISSUE THREAD

**Issue by m4s0** [cawa87/zf2-blog#3]
Hi, I want to congratulate you I like your project.
I am new to zend framework 2 and I'm studying it. 
I can not login to the backend of your project, to manage the news, and more. 

What is the route, how can I do to go to the backend? 

Thanks in advance, 
Marco

**Comment by cawa87** [comment]
Nice to hear it, to you admin part you need to register, and manual change in database your role, only 'admin' role is grand to use the admin part. If you have more questions u can contact me via skype:cawakharkov

**Comment by m4s0** [comment]
thanks

**Comment by cawa87** [comment]
@m4s0  welcome
But soon i'm moving application at a new platform build on sf2, so theres will no more updates
